spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:h2:mem:spring-boot-inmemory
    driver-class-name: org.h2.Driver
    password: test
    username: test
  h2:
    console:
      enabled: true