spring:
  webflux:
    base-path: /demo-hexagon
  application:
    name: demo-hexagonal-architecture
  profiles:
    include: infrastructure
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_hexagon?createDatabaseIfNotExists=true
    password: postgres
    username: postgres
    schema: classpath*:scripts/ddl.sql
    platform: postgres